swagger: '2.0'
info:
  title: test - gRPC Gateway docs
  description: A REST interface for state queries.
  version: 1.0.0
paths:
  /v1/test/balance:
    get:
      operationId: Balance
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              userid:
                type: string
              items:
                type: array
                items:
                  type: object
                  properties:
                    amt:
                      type: string
                    denom:
                      type: string
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              error:
                type: string
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    type_url:
                      type: string
                    value:
                      type: string
                      format: byte
      parameters:
        - name: userid
          in: query
          required: false
          type: string
      tags:
        - Query
  /v1/test/deposit:
    post:
      operationId: Deposit
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              error:
                type: string
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    type_url:
                      type: string
                    value:
                      type: string
                      format: byte
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              userid:
                type: string
              amt:
                type: string
              denom:
                type: string
              memo:
                type: string
      tags:
        - Msg
  /v1/test/deposit-history:
    get:
      operationId: DepositHistory
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              from:
                type: string
              history:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    from:
                      type: string
                    to:
                      type: string
                    amt:
                      type: string
                    denom:
                      type: string
                    memo:
                      type: string
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              error:
                type: string
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    type_url:
                      type: string
                    value:
                      type: string
                      format: byte
      parameters:
        - name: userid
          in: query
          required: false
          type: string
      tags:
        - Query
  /v1/test/send:
    post:
      operationId: Send
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              error:
                type: string
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    type_url:
                      type: string
                    value:
                      type: string
                      format: byte
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              from:
                type: string
              to:
                type: string
              amt:
                type: string
              denom:
                type: string
              memo:
                type: string
      tags:
        - Msg
  /v1/test/send-history:
    get:
      operationId: SendHistory
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              from:
                type: string
              history:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    from:
                      type: string
                    to:
                      type: string
                    amt:
                      type: string
                    denom:
                      type: string
                    memo:
                      type: string
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              error:
                type: string
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    type_url:
                      type: string
                    value:
                      type: string
                      format: byte
      parameters:
        - name: userid
          in: query
          required: false
          type: string
      tags:
        - Query
  /v1/test/withdraw:
    post:
      operationId: Withdraw
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              error:
                type: string
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    type_url:
                      type: string
                    value:
                      type: string
                      format: byte
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              userid:
                type: string
              amt:
                type: string
              denom:
                type: string
              memo:
                type: string
      tags:
        - Msg
definitions:
  google.protobuf.Any:
    type: object
    properties:
      type_url:
        type: string
      value:
        type: string
        format: byte
  grpc.gateway.runtime.Error:
    type: object
    properties:
      error:
        type: string
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          properties:
            type_url:
              type: string
            value:
              type: string
              format: byte
  test.proto.BalanceItem:
    type: object
    properties:
      amt:
        type: string
      denom:
        type: string
  test.proto.MsgDeposit:
    type: object
    properties:
      userid:
        type: string
      amt:
        type: string
      denom:
        type: string
      memo:
        type: string
  test.proto.MsgDepositResp:
    type: object
  test.proto.MsgSend:
    type: object
    properties:
      from:
        type: string
      to:
        type: string
      amt:
        type: string
      denom:
        type: string
      memo:
        type: string
  test.proto.MsgSendResp:
    type: object
  test.proto.MsgWithdraw:
    type: object
    properties:
      userid:
        type: string
      amt:
        type: string
      denom:
        type: string
      memo:
        type: string
  test.proto.MsgWithdrawResp:
    type: object
  test.proto.QueryBalanceResp:
    type: object
    properties:
      userid:
        type: string
      items:
        type: array
        items:
          type: object
          properties:
            amt:
              type: string
            denom:
              type: string
  test.proto.QueryDepositHistoryResp:
    type: object
    properties:
      from:
        type: string
      history:
        type: array
        items:
          type: object
          properties:
            type:
              type: string
            from:
              type: string
            to:
              type: string
            amt:
              type: string
            denom:
              type: string
            memo:
              type: string
  test.proto.QuerySendHistoryResp:
    type: object
    properties:
      from:
        type: string
      history:
        type: array
        items:
          type: object
          properties:
            type:
              type: string
            from:
              type: string
            to:
              type: string
            amt:
              type: string
            denom:
              type: string
            memo:
              type: string
  test.proto.SendHistoryItem:
    type: object
    properties:
      type:
        type: string
      from:
        type: string
      to:
        type: string
      amt:
        type: string
      denom:
        type: string
      memo:
        type: string
